/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_liguangchun_ndkdemo2_NdkHelper */

#ifndef _Included_com_example_liguangchun_ndkdemo2_NdkHelper
#define _Included_com_example_liguangchun_ndkdemo2_NdkHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_liguangchun_ndkdemo2_NdkHelper
 * Method:    getStr
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_example_liguangchun_ndkdemo2_NdkHelper_getStr
  (JNIEnv *, jclass);

/*
 * Class:     com_example_liguangchun_ndkdemo2_NdkHelper
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_liguangchun_ndkdemo2_NdkHelper_init
  (JNIEnv *, jobject);

/*
 * Class:     com_example_liguangchun_ndkdemo2_NdkHelper
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_liguangchun_ndkdemo2_NdkHelper_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
